//! §7 TODO.md view tests: full render scenario, empty-section omission, ordering rules,
//! and wikilink rules including hostile stems.

use std::collections::BTreeMap;

use chrono::{DateTime, TimeZone, Utc};
use restask::config::VaultConfig;
use restask::domain::{
    ListSlug, LocalDate, LocalDateTime, Priority, SourceRef, Status, Task, TaskUid, When,
};
use restask::markdown::mutator::{Mutation, WhenField};
use restask::markdown::todo_view::{
    inbox_line, looks_like_mirror, mirror_edits, mirror_line, render, MARKER,
};

const U1: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpb";
const U2: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpc";
const U3: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpd";
const U4: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpe";
const U5: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpf";
const U6: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdpg";
const U7: &str = "restask-01jzq4tsvg2c9xkw7n5m8rhdph";

fn fixed_time() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 9, 22, 12, 0, 0).unwrap()
}

fn task(uid: &str, text: &str) -> Task {
    Task {
        uid: TaskUid::parse(uid).unwrap(),
        list: ListSlug::from_name("home").unwrap(),
        text: text.to_string(),
        status: Status::Active,
        priority: None,
        due: None,
        start: None,
        scheduled: None,
        recurrence: None,
        created: None,
        parent: None,
        source: SourceRef {
            path: "TODO.md".to_string(),
            line: 1,
        },
        source_heading: None,
        source_mtime: fixed_time(),
        last_modified: fixed_time(),
    }
}

fn vault_task(uid: &str, text: &str, path: &str, line: usize) -> Task {
    let mut task = task(uid, text);
    task.source = SourceRef {
        path: path.to_string(),
        line,
    };
    task
}

fn date(value: &str) -> LocalDate {
    LocalDate::parse(value).unwrap()
}

/// The frontmatter block `render` emits for the default (§14) inbox list.
const FRONTMATTER: &str = "---\nrestask-list: inbox\n---\n\n";

#[test]
fn render_full_scenario() {
    let mut tasks = BTreeMap::new();

    let mut buy_milk = task(U1, "Buy milk");
    buy_milk.created = Some(date("2026-09-22"));
    tasks.insert(buy_milk.uid.clone(), buy_milk);

    let mut ssl = vault_task(
        U2,
        "Setup SSL certificate renew alert",
        "Home Lab Test.md",
        6,
    );
    ssl.priority = Some(Priority::Highest);
    ssl.source_heading = Some("To Do".to_string());
    tasks.insert(ssl.uid.clone(), ssl);

    let mut review = vault_task(U3, "Review architecture plan", "Project Alpha Test.md", 7);
    review.priority = Some(Priority::High);
    review.source_heading = Some("Tasks".to_string());
    tasks.insert(review.uid.clone(), review);

    let mut docs = vault_task(U4, "Update documentation", "Project Alpha Test.md", 8);
    docs.priority = Some(Priority::Medium);
    docs.source_heading = Some("Tasks".to_string());
    tasks.insert(docs.uid.clone(), docs);

    let mut backup = vault_task(
        U5,
        "Configure automatic backup to NAS",
        "Home Lab Test.md",
        6,
    );
    backup.priority = Some(Priority::Medium);
    backup.source_heading = Some("To Do".to_string());
    tasks.insert(backup.uid.clone(), backup);

    let mut talos = vault_task(U6, "Deploy Talos Linux on mini-PC", "Home Lab Test.md", 7);
    talos.priority = Some(Priority::Low);
    talos.source_heading = Some("To Do".to_string());
    tasks.insert(talos.uid.clone(), talos);

    let mut trash = task(U7, "Take out trash");
    trash.priority = Some(Priority::Low);
    trash.status = Status::Completed {
        on: date("2026-09-19"),
    };
    tasks.insert(trash.uid.clone(), trash);

    let out = render(&tasks, &VaultConfig::default());
    assert_eq!(
        out,
        concat!(
            "---\n",
            "restask-list: inbox\n",
            "---\n",
            "\n",
            "<!-- AUTOGENERATED BY Restask -->\n",
            "\n",
            "# TODO\n",
            "\n",
            "## Inbox\n",
            "- [ ] Buy milk ➕ 2026-09-22 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb\n",
            "\n",
            "## 🔺 Highest Priority\n",
            "- [ ] Setup SSL certificate renew alert 🔺 [[Home Lab Test#To Do|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpc\n",
            "\n",
            "## ⏫ High Priority\n",
            "- [ ] Review architecture plan ⏫ [[Project Alpha Test#Tasks|Project Alpha Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpd\n",
            "\n",
            "## 🔼 Medium Priority\n",
            "- [ ] Configure automatic backup to NAS 🔼 [[Home Lab Test#To Do|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpf\n",
            "- [ ] Update documentation 🔼 [[Project Alpha Test#Tasks|Project Alpha Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpe\n",
            "\n",
            "## 🔽 Low Priority\n",
            "- [ ] Deploy Talos Linux on mini-PC 🔽 [[Home Lab Test#To Do|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpg\n",
            "\n",
            "## Done\n",
            "- [x] Take out trash 🔽 ✅ 2026-09-19 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdph\n",
        )
    );
}

#[test]
fn empty_sections_are_omitted() {
    let mut tasks = BTreeMap::new();
    tasks.insert(task(U1, "Buy milk").uid.clone(), task(U1, "Buy milk"));
    let out = render(&tasks, &VaultConfig::default());
    assert_eq!(
        out,
        concat!(
            "---\n",
            "restask-list: inbox\n",
            "---\n",
            "\n",
            "<!-- AUTOGENERATED BY Restask -->\n",
            "\n",
            "# TODO\n",
            "\n",
            "## Inbox\n",
            "- [ ] Buy milk 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb\n",
            "\n",
            "## Done\n",
        )
    );
    assert!(!out.contains("Priority"));
    assert!(out.starts_with(FRONTMATTER));
}

#[test]
fn done_newest_on_top_and_completed_vault_tasks_omitted() {
    let mut tasks = BTreeMap::new();

    let mut first = task(U2, "B");
    first.status = Status::Completed {
        on: date("2026-09-19"),
    };
    tasks.insert(first.uid.clone(), first);

    let mut second = task(U3, "C");
    second.status = Status::Completed {
        on: date("2026-09-20"),
    };
    tasks.insert(second.uid.clone(), second);

    let mut third = task(U4, "D");
    third.status = Status::Completed {
        on: date("2026-09-19"),
    };
    tasks.insert(third.uid.clone(), third);

    let mut vault_done = vault_task(U1, "A", "Other.md", 3);
    vault_done.priority = Some(Priority::High);
    vault_done.status = Status::Completed {
        on: date("2026-09-21"),
    };
    tasks.insert(vault_done.uid.clone(), vault_done);

    let out = render(&tasks, &VaultConfig::default());
    assert!(!out.contains("- [x] A "));
    assert!(!out.contains("## ⏫ High Priority"));
    assert_eq!(
        out,
        concat!(
            "---\n",
            "restask-list: inbox\n",
            "---\n",
            "\n",
            "<!-- AUTOGENERATED BY Restask -->\n",
            "\n",
            "# TODO\n",
            "\n",
            "## Done\n",
            "- [x] C ✅ 2026-09-20 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpd\n",
            "- [x] D ✅ 2026-09-19 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpe\n",
            "- [x] B ✅ 2026-09-19 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpc\n",
        )
    );
}

#[test]
fn render_emits_the_configured_inbox_list() {
    let cfg = VaultConfig {
        inbox_list: "tasks".to_string(),
        ..VaultConfig::default()
    };
    let out = render(&BTreeMap::new(), &cfg);
    assert!(out.starts_with("---\nrestask-list: tasks\n---\n\n"));
}

#[test]
fn mirror_line_rules() {
    let mut linked = vault_task(U1, "Write docs", "Home Lab Test.md", 5);
    linked.source_heading = Some("To Do".to_string());
    assert_eq!(
        mirror_line(&linked),
        "- [ ] Write docs [[Home Lab Test#To Do|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );

    let mut no_heading = vault_task(U1, "Write docs", "Home Lab Test.md", 5);
    no_heading.status = Status::Completed {
        on: date("2026-09-19"),
    };
    assert_eq!(
        mirror_line(&no_heading),
        "- [x] Write docs [[Home Lab Test|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );

    let hostile = vault_task(U1, "Weird", "We[ird|Task#1.md", 2);
    assert_eq!(
        mirror_line(&hostile),
        "- [ ] Weird We[ird|Task#1 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );

    let mut hostile_heading = vault_task(U1, "Weird", "We[ird|Task#1.md", 2);
    hostile_heading.source_heading = Some("Head".to_string());
    assert_eq!(
        mirror_line(&hostile_heading),
        "- [ ] Weird We[ird|Task#1#Head 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );

    let mut scheduled = vault_task(U1, "Write docs", "Home Lab Test.md", 5);
    scheduled.priority = Some(Priority::Medium);
    scheduled.start = Some(When::Date(date("2026-09-21")));
    scheduled.scheduled = Some(When::DateTime(
        LocalDateTime::parse("2026-09-22 08:00").unwrap(),
    ));
    scheduled.due = Some(When::Date(date("2026-09-23")));
    assert_eq!(
        mirror_line(&scheduled),
        "- [ ] Write docs 🔼 🛫 2026-09-21 ⏳ 2026-09-22 08:00 📅 2026-09-23 [[Home Lab Test|Home Lab Test]] 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );
}

#[test]
fn inbox_line_full_canonical() {
    let mut full = task(U1, "Plan week");
    full.priority = Some(Priority::Medium);
    full.start = Some(When::Date(date("2026-09-21")));
    full.scheduled = Some(When::DateTime(
        LocalDateTime::parse("2026-09-22 08:00").unwrap(),
    ));
    full.due = Some(When::DateTime(
        LocalDateTime::parse("2026-09-23 17:30").unwrap(),
    ));
    full.status = Status::Completed {
        on: date("2026-09-20"),
    };
    full.created = Some(date("2026-09-01"));
    assert_eq!(
        inbox_line(&full),
        "- [x] Plan week 🔼 🛫 2026-09-21 ⏳ 2026-09-22 08:00 📅 2026-09-23 17:30 ✅ 2026-09-20 ➕ 2026-09-01 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpb"
    );

    assert_eq!(
        inbox_line(&task(U2, "Buy milk")),
        "- [ ] Buy milk 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdpc"
    );
}

#[test]
fn marker_constant() {
    assert_eq!(MARKER, "<!-- AUTOGENERATED BY Restask -->");
}

#[test]
fn unprioritized_note_tasks_stay_in_their_note() {
    // README: "Tasks without an assigned priority remain solely in their source file."
    let mut tasks = BTreeMap::new();
    let idea = vault_task(U1, "Just an idea", "Notes/Ideas.md", 3);
    tasks.insert(idea.uid.clone(), idea);
    let quick = task(U2, "Quick capture");
    tasks.insert(quick.uid.clone(), quick);

    let out = render(&tasks, &VaultConfig::default());
    assert!(!out.contains("Just an idea"));
    assert!(out.contains("## Inbox\n- [ ] Quick capture 🆔"));
}

#[test]
fn lines_with_empty_text_have_no_double_spaces() {
    let mut empty = vault_task(U1, "", "Notes/A.md", 1);
    empty.priority = Some(Priority::High);
    assert_eq!(mirror_line(&empty), format!("- [ ] ⏫ [[A|A]] 🆔 {U1}"));
    assert_eq!(inbox_line(&task(U2, "")), format!("- [ ] 🆔 {U2}"));
}

// ---- mirror edits: TODO.md is a two-way view ----

/// A vault with one prioritized, dated note task, and the render that shows it.
fn mirrored() -> (BTreeMap<TaskUid, Task>, String) {
    let mut tasks = BTreeMap::new();
    let mut plan = vault_task(U1, "Review the plan", "Projects/Alpha.md", 4);
    plan.priority = Some(Priority::High);
    plan.due = Some(When::Date(date("2026-09-25")));
    plan.source_heading = Some("Tasks".to_string());
    tasks.insert(plan.uid.clone(), plan);
    let quick = task(U2, "Quick capture");
    tasks.insert(quick.uid.clone(), quick);
    let rendered = render(&tasks, &VaultConfig::default());
    (tasks, rendered)
}

fn edits_for(current: &str, rendered: &str, tasks: &BTreeMap<TaskUid, Task>) -> Vec<Mutation> {
    let mut edits = mirror_edits(
        current,
        rendered,
        tasks,
        &VaultConfig::default(),
        date("2026-09-22"),
    );
    assert!(edits.len() <= 1, "all edits target the one source note");
    edits.remove("Projects/Alpha.md").unwrap_or_default()
}

#[test]
fn an_untouched_view_yields_no_edits() {
    let (tasks, rendered) = mirrored();
    assert!(edits_for(&rendered, &rendered, &tasks).is_empty());
}

#[test]
fn checking_a_mirror_line_completes_the_source_task() {
    let (tasks, rendered) = mirrored();
    let current = rendered.replace("- [ ] Review the plan", "- [x] Review the plan");
    let uid = TaskUid::parse(U1).unwrap();
    assert_eq!(
        edits_for(&current, &rendered, &tasks),
        vec![
            Mutation::SetStatus {
                uid: uid.clone(),
                checked: true,
                completed_on: Some(date("2026-09-22")),
            },
            Mutation::MoveToDone { uid },
        ]
    );
}

#[test]
fn a_plugin_style_completion_keeps_its_own_date() {
    // The plugin stamps ✅ and moves the line under `## Done` inside TODO.md.
    let (tasks, rendered) = mirrored();
    let line = rendered
        .lines()
        .find(|line| line.contains("Review the plan"))
        .unwrap()
        .to_string();
    let moved = line
        .replace("- [ ]", "- [x]")
        .replace(" 🆔", " ✅ 2026-09-20 🆔");
    let current = rendered.replace(&format!("{line}\n"), "") + &moved + "\n";
    let edits = edits_for(&current, &rendered, &tasks);
    assert_eq!(
        edits[0],
        Mutation::SetStatus {
            uid: TaskUid::parse(U1).unwrap(),
            checked: true,
            completed_on: Some(date("2026-09-20")),
        }
    );
}

#[test]
fn field_edits_on_a_mirror_line_reach_the_source() {
    let (tasks, rendered) = mirrored();
    let current = rendered
        .replace("Review the plan ⏫", "Review the whole plan 🔺")
        .replace("📅 2026-09-25", "📅 2026-10-01 09:00");
    let uid = TaskUid::parse(U1).unwrap();
    assert_eq!(
        edits_for(&current, &rendered, &tasks),
        vec![
            Mutation::EditText {
                uid: uid.clone(),
                text: "Review the whole plan".to_string(),
            },
            Mutation::SetPriority {
                uid: uid.clone(),
                priority: Some(Priority::Highest),
            },
            Mutation::SetWhen {
                uid,
                field: WhenField::Due,
                value: Some(When::DateTime(
                    LocalDateTime::parse("2026-10-01 09:00").unwrap()
                )),
            },
        ]
    );
}

#[test]
fn a_stale_view_is_not_an_edit_and_the_note_wins_conflicts() {
    let (mut tasks, rendered) = mirrored();
    // The note changed after the render: the view is merely stale.
    let uid = TaskUid::parse(U1).unwrap();
    tasks.get_mut(&uid).unwrap().priority = Some(Priority::Low);
    assert!(edits_for(&rendered, &rendered, &tasks).is_empty());

    // The user re-prioritized in the view too: the note's own change wins that field,
    // while an untouched-in-the-note field (the checkbox) still carries over.
    let current = rendered
        .replace("Review the plan ⏫", "Review the plan 🔺")
        .replace("- [ ] Review", "- [x] Review");
    let edits = edits_for(&current, &rendered, &tasks);
    assert!(edits
        .iter()
        .all(|edit| !matches!(edit, Mutation::SetPriority { .. })));
    assert!(matches!(
        edits[0],
        Mutation::SetStatus { checked: true, .. }
    ));
}

#[test]
fn inbox_lines_and_unknown_lines_are_never_mirror_edits() {
    let (tasks, rendered) = mirrored();
    let current = rendered.replace("- [ ] Quick capture", "- [x] Quick capture reworded")
        + "- [ ] typed by hand\n- [ ] pasted 🆔 restask-01jzq4tsvg2c9xkw7n5m8rhdph\n";
    assert!(edits_for(&current, &rendered, &tasks).is_empty());
}

#[test]
fn mirror_shape_is_a_wikilink_right_before_the_uid() {
    assert!(looks_like_mirror(&format!(
        "- [ ] Review ⏫ [[Alpha#Tasks|Alpha]] 🆔 {U1}"
    )));
    // An inbox task that merely mentions a note is a task of its own.
    assert!(!looks_like_mirror(&format!(
        "- [ ] Call [[John]] ➕ 2026-09-22 🆔 {U1}"
    )));
    assert!(!looks_like_mirror("- [ ] Call [[John]]"));
}
