//! TODO.md view (§7): deterministic full-file render of the engine-owned inbox view, and
//! the reverse direction — recognising what the user edited inside it. Pure — no I/O.

use std::collections::BTreeMap;
use std::hash::Hasher;

use fnv::FnvHasher;

use crate::config::VaultConfig;
use crate::domain::{LocalDate, Priority, Status, Task, TaskUid};
use crate::markdown::mutator::{canonical_line, fmt_when, Mutation, WhenField};
use crate::markdown::parser::{parse, ParsedTask, TaskDraft};

/// Opens the seal line of a render (§7.2): a property of the view's frontmatter block,
/// below `restask-list`. Nothing restask writes goes into the body but the view itself.
pub(crate) const SEAL_PREFIX: &str = "restask-render: ";

/// The disclaimer comment views carried before the seal moved into the frontmatter. Never
/// written; read only to recognise such a view as one of restask's ([`is_view`]).
const LEGACY_MARKER: &str = "<!-- AUTOGENERATED BY Restask -->";

/// The seal as a comment line in the body, as earlier renders wrote it. Never written, and
/// it seals nothing any more; read only by [`is_view`].
const LEGACY_SEAL_PREFIX: &str = "<!-- restask-render: ";

/// The digest a seal carries: FNV-1a (64-bit) over the view's text without its seal line,
/// as 16 lowercase hex digits.
pub(crate) fn digest(unsealed: &str) -> String {
    let mut hasher = FnvHasher::default();
    hasher.write(unsealed.as_bytes());
    format!("{:016x}", hasher.finish())
}

/// The seal line (with its line break) for a view whose text without it is `unsealed`.
fn seal_line(unsealed: &str) -> String {
    format!("{SEAL_PREFIX}{}\n", digest(unsealed))
}

/// Byte range of the seal line of `contents`, line break included: the first line of the
/// frontmatter block that opens with the seal's key. `None` when the text has no
/// frontmatter block, or the block has no such line.
pub(crate) fn seal_range(contents: &str) -> Option<(usize, usize)> {
    let mut at = contents.strip_prefix("---\n").map(|_| 4)?;
    loop {
        let length = contents[at..].find('\n')?;
        let line = &contents[at..at + length];
        if line == "---" {
            return None;
        }
        if line.starts_with(SEAL_PREFIX) {
            return Some((at, at + length + 1));
        }
        at += length + 1;
    }
}

/// The digest the seal line of `contents` claims, right or not: which render the text
/// is, or was before it was edited. `None` when it has no seal line.
pub(crate) fn seal_claim(contents: &str) -> Option<&str> {
    seal_range(contents).map(|(start, end)| &contents[start + SEAL_PREFIX.len()..end - 1])
}

/// `true` when `current` is this engine's last render (`rendered`) with edits made in it,
/// and whole: it still claims that render's seal, and it reaches down to the `## Done`
/// heading every render ends with. Only then does a line that is *missing* say anything
/// (§7.1): in a view edited from another render the line may never have been there, and
/// a file cut short lost its lines to no one's decision.
fn edited_from(current: &ViewText<'_>, rendered: &ViewText<'_>) -> bool {
    current.claim.is_some()
        && current.claim == rendered.claim
        && current.body.lines().any(|line| line == current.done_line)
}

/// One view as [`edits_between`] compares it: TODO.md, or the view a root note holds
/// (§7.6).
pub(crate) struct ViewText<'a> {
    /// The text of the view: all of TODO.md, or the TODO section of a root note.
    pub body: &'a str,
    /// The digest its seal line claims, right or not (§7.2).
    pub claim: Option<&'a str>,
    /// Whether the seal matches the text: a render, with no edit in it.
    pub sealed: bool,
    /// The heading line every render of this view ends with — the proof that the text
    /// is whole (§7.1).
    pub done_line: &'a str,
}

/// `true` when `contents` is a view exactly as some device rendered it (§7.2): its
/// frontmatter carries a seal, and the seal matches the rest of the text. Such a view
/// holds no edit of the user's — whoever sealed it had carried them all to the notes
/// first. A view the user changed since (in any editor) no longer matches its seal.
pub fn is_sealed(contents: &str) -> bool {
    let Some((start, end)) = seal_range(contents) else {
        return false;
    };
    let claimed = &contents[start + SEAL_PREFIX.len()..end - 1];
    let unsealed = format!("{}{}", &contents[..start], &contents[end..]);
    claimed == digest(&unsealed)
}

/// `true` when `contents` is a view some restask rendered, edited since or not: its
/// frontmatter carries a seal line, or it has the disclaimer or the seal comment of an
/// earlier render. Tells the inbox file of a vault that is set up from a file restask
/// never wrote (`restask setup`, `restask doctor`); it is never how a pass finds the
/// view — that is the inbox path.
pub fn is_view(contents: &str) -> bool {
    seal_range(contents).is_some()
        || contents
            .lines()
            .any(|line| line.trim() == LEGACY_MARKER || line.starts_with(LEGACY_SEAL_PREFIX))
}

/// Heading text of a priority's section in the view (§7), without the `## `.
pub(crate) fn priority_heading(priority: Priority) -> String {
    format!("{} {} Priority", priority.emoji(), priority.heading())
}

/// The priority a section of the view stands for (§7.4): `heading` is a task's nearest
/// heading, and the answer is `Some` only for the text of one of the five priority
/// sections exactly as the render writes it. The scan asks this for a line typed into
/// TODO.md, so that a task written under a priority's heading takes that priority.
pub fn section_priority(heading: &str) -> Option<Priority> {
    Priority::ALL
        .into_iter()
        .find(|priority| priority_heading(*priority) == heading)
}

/// Heading text of the section for the inbox file's own tasks without a priority (§7).
pub(crate) const NO_PRIORITY_HEADING: &str = "No Priority";

/// The priority an active line takes from being **moved** to another section of the view
/// (§7.4): `Some(priority)` when the user moved it, `None` when the line is where the
/// render put it, or says itself what it wants. `now` is the line in the live file, `was`
/// the same task in the engine's last render. A move is a line under another heading
/// with the priority emoji it was rendered with — the heading of a priority section gives
/// that priority, `No Priority` takes it away. A changed emoji is the user naming the
/// priority, and wins; a move under `Done` or any other heading says nothing.
fn moved_priority(now: &ParsedTask, was: &ParsedTask) -> Option<Option<Priority>> {
    if now.draft.checked
        || was.draft.checked
        || now.heading == was.heading
        || now.draft.priority != was.draft.priority
    {
        return None;
    }
    let heading = now.heading.as_deref()?;
    let target = match section_priority(heading) {
        Some(priority) => Some(priority),
        None if heading == NO_PRIORITY_HEADING => None,
        None => return None,
    };
    (target != now.draft.priority).then_some(target)
}

/// `[x]` or `[ ]` checkbox per lifecycle state.
fn checkbox(task: &Task) -> &'static str {
    match task.status {
        Status::Active => "[ ]",
        Status::Completed { .. } => "[x]",
    }
}

/// Filename without its `.md` suffix (§7 source stem).
fn stem_of(path: &str) -> &str {
    let file = path.rsplit('/').next().unwrap_or(path);
    file.strip_suffix(".md").unwrap_or(file)
}

/// The wikilink for the task's source note, or plain text when the stem is hostile (§7):
/// stems containing `[`, `]`, `|` or `#` cannot appear inside a `[[...|...]]` link, so the
/// link is replaced by plain text.
fn source_link(task: &Task) -> String {
    let stem = stem_of(&task.source.path);
    let suffix = match &task.source_heading {
        Some(heading) => format!("#{heading}"),
        None => String::new(),
    };
    if stem.contains(['[', ']', '|', '#']) {
        format!("{stem}{suffix}")
    } else {
        format!("[[{stem}{suffix}|{stem}]]")
    }
}

/// Renders a task sourced from a vault note as a mirror line (§7):
/// `- [<check>] <text> <priority?> <🔁?><🛫?><⏳?><📅?> [[<stem>#<heading>|<stem>]] 🆔 <uid>`;
/// `#<heading>` is omitted when the task has no preceding heading.
pub fn mirror_line(task: &Task) -> String {
    let mut parts: Vec<String> = vec![format!("- {}", checkbox(task))];
    if !task.text.is_empty() {
        parts.push(task.text.clone());
    }
    if let Some(priority) = task.priority {
        parts.push(priority.emoji().to_string());
    }
    if let Some(rule) = &task.recurrence {
        parts.push(format!("🔁 {}", rule.to_text()));
    }
    if let Some(when) = task.start {
        parts.push(format!("🛫 {}", fmt_when(when)));
    }
    if let Some(when) = task.scheduled {
        parts.push(format!("⏳ {}", fmt_when(when)));
    }
    if let Some(when) = task.due {
        parts.push(format!("📅 {}", fmt_when(when)));
    }
    parts.push(source_link(task));
    parts.push(format!("🆔 {}", task.uid));
    parts.join(" ")
}

/// Renders a TODO.md-sourced task as a full canonical line without wikilink (§7):
/// `- [<check>] <text> <priority?> <🛫?><⏳?><📅?><✅?><➕?><📁?> 🆔 <uid>`. The line names
/// its calendar (`📁`) when that is not the one unmarked lines belong to,
/// `cfg.inbox_list` (§7.5).
pub fn inbox_line(task: &Task, cfg: &VaultConfig) -> String {
    let mut draft = TaskDraft::from(task);
    if task.list.as_str() != cfg.inbox_list {
        draft.list = Some(task.list.clone());
    }
    canonical_line("", '-', &draft)
}

/// The completion date of a task, if completed.
pub(crate) fn completed_on(task: &Task) -> Option<LocalDate> {
    match task.status {
        Status::Completed { on } => Some(on),
        Status::Active => None,
    }
}

/// The rendered line for a task: full canonical line for TODO.md-sourced tasks, mirror
/// line (with wikilink) for vault-note tasks.
fn line_for(task: &Task, cfg: &VaultConfig) -> String {
    if task.source.path == cfg.inbox_file {
        inbox_line(task, cfg)
    } else {
        mirror_line(task)
    }
}

/// Idempotent full render (§7). `vault_tasks` holds every routed, registered task (all
/// lists); the same task set produces byte-identical output. The file opens with its
/// frontmatter block — `restask-list: <inbox_list>` (§5.2) and the seal (§7.2) — and the
/// `# <inbox-file-stem>` title directly below it, with no blank line between the two.
/// Sections — the five priority
/// sections, then `## No Priority` — are emitted only when non-empty, in that fixed order;
/// `## Done` is always present. Each priority section holds active tasks with that priority
/// ((source path asc, line) asc); `## No Priority` holds the inbox file's own active tasks
/// without priority (ULID asc); `## Done` holds only TODO.md-sourced completed tasks
/// newest-on-top (completed date desc, then ULID desc). Completed vault-note tasks never
/// appear (they live under their source file's Done heading), with or without a priority.
pub fn render(vault_tasks: &BTreeMap<TaskUid, Task>, cfg: &VaultConfig) -> String {
    let mut unprioritized: Vec<&Task> = Vec::new();
    let mut prioritized: [Vec<&Task>; 5] =
        [Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new()];
    let mut done: Vec<&Task> = Vec::new();

    for task in vault_tasks.values() {
        match task.status {
            Status::Active => match task.priority {
                Some(priority) => {
                    let slot = Priority::ALL
                        .iter()
                        .position(|candidate| *candidate == priority)
                        .unwrap_or_default();
                    prioritized[slot].push(task);
                }
                // The no-priority section is the inbox file's own unprioritized tasks; an
                // unprioritized note task stays in its note only (README).
                None if task.source.path == cfg.inbox_file => unprioritized.push(task),
                None => {}
            },
            Status::Completed { .. } => {
                if task.source.path == cfg.inbox_file {
                    done.push(task);
                }
            }
        }
    }
    for section in &mut prioritized {
        section
            .sort_by(|a, b| (&a.source.path, a.source.line).cmp(&(&b.source.path, b.source.line)));
    }
    done.sort_by(|a, b| {
        completed_on(b)
            .cmp(&completed_on(a))
            .then_with(|| b.uid.as_str().cmp(a.uid.as_str()))
    });

    let mut head = String::new();
    head.push_str("---\nrestask-list: ");
    head.push_str(&cfg.inbox_list);
    head.push('\n');
    let mut out = String::from("---\n");
    out.push_str(&format!("# {}\n\n", stem_of(&cfg.inbox_file)));

    let mut sections: Vec<String> = Vec::new();
    for (slot, priority) in Priority::ALL.iter().enumerate() {
        if prioritized[slot].is_empty() {
            continue;
        }
        let mut section = format!("## {}\n", priority_heading(*priority));
        for task in &prioritized[slot] {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    if !unprioritized.is_empty() {
        let mut section = format!("## {NO_PRIORITY_HEADING}\n");
        for task in &unprioritized {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    {
        let mut section = String::from("## Done\n");
        for task in &done {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    out.push_str(&sections.join("\n"));
    // The seal closes the frontmatter block and covers everything else (§7.2).
    let seal = seal_line(&format!("{head}{out}"));
    format!("{head}{seal}{out}")
}

/// What the user changed inside TODO.md since the engine last rendered it that the scan
/// cannot read off the lines themselves, expressed as mutations keyed by vault-relative
/// path: edits of **mirror lines**, which belong in the source notes, and — for mirror
/// lines and the view's own lines alike — the priority a line takes from being moved to
/// another section (§7.4), which for a line of the view's own is a mutation of the inbox
/// file.
///
/// A mirror line is "the exact same task" as its source line (README), so checking it
/// off, re-prioritizing it, re-dating it or rewording it in TODO.md must reach the note.
/// `rendered` is the engine's own last render; a mirror line that still equals it was not
/// touched (it may merely be stale, which the next render fixes). A field the user changed
/// is applied only when the source still shows the rendered value — if the note changed
/// that field too, the note wins. A sealed view (§7.2) carries no edits at all.
///
/// A mirror line the user **deleted** deletes the task in its note — when the view is
/// this engine's last render edited (`edited_from`), the task's UID is nowhere in it any
/// more, and the note still shows the task as it was rendered. Anything less is absence
/// without a cause, and the next render puts the line back.
pub fn mirror_edits(
    current: &str,
    rendered: &str,
    local: &BTreeMap<TaskUid, Task>,
    cfg: &VaultConfig,
    today: LocalDate,
) -> BTreeMap<String, Vec<Mutation>> {
    let view = |text| ViewText {
        body: text,
        claim: seal_claim(text),
        sealed: is_sealed(text),
        done_line: "## Done",
    };
    edits_between(
        &view(current),
        &view(rendered),
        local,
        &cfg.inbox_file,
        cfg,
        today,
    )
}

/// [`mirror_edits`] for any view: `current` is the view as it is in the vault, `rendered`
/// this engine's last render of it, `own_path` the file the view is in — a task whose
/// source is that file is a line of the view's own.
pub(crate) fn edits_between(
    current: &ViewText<'_>,
    rendered: &ViewText<'_>,
    local: &BTreeMap<TaskUid, Task>,
    own_path: &str,
    cfg: &VaultConfig,
    today: LocalDate,
) -> BTreeMap<String, Vec<Mutation>> {
    let mut edits: BTreeMap<String, Vec<Mutation>> = BTreeMap::new();
    // A sealed view is some device's render, not an edit: where it differs from this
    // engine's last render, the notes are what changed — and they may still be in transit.
    if current.body == rendered.body || current.sealed {
        return edits;
    }
    let mut shown: BTreeMap<TaskUid, ParsedTask> = BTreeMap::new();
    for task in parse(rendered.body, cfg).tasks {
        if let Some(uid) = task.draft.uid.clone() {
            shown.entry(uid).or_insert(task);
        }
    }
    let mut seen: Vec<TaskUid> = Vec::new();
    for line in parse(current.body, cfg).tasks {
        let Some(uid) = line.draft.uid.clone() else {
            continue;
        };
        let (Some(source), Some(was)) = (local.get(&uid), shown.get(&uid)) else {
            continue;
        };
        if seen.contains(&uid) {
            continue;
        }
        seen.push(uid.clone());
        let moved = moved_priority(&line, was);
        if source.source.path == own_path {
            // A line of the view's own says everything else itself; the scan reads it.
            if let Some(priority) = moved {
                edits
                    .entry(source.source.path.clone())
                    .or_default()
                    .push(Mutation::SetPriority { uid, priority });
            }
            continue;
        }
        let was = &was.draft;
        let mut now = line.draft;
        if let Some(priority) = moved {
            now.priority = priority;
        }
        let mut ops: Vec<Mutation> = Vec::new();
        let mut tail: Vec<Mutation> = Vec::new();

        let source_checked = matches!(source.status, Status::Completed { .. });
        if now.checked != was.checked && source_checked == was.checked {
            if now.checked {
                ops.push(Mutation::SetStatus {
                    uid: uid.clone(),
                    checked: true,
                    completed_on: Some(now.completed_on.unwrap_or(today)),
                });
                tail.push(Mutation::MoveToDone { uid: uid.clone() });
            } else {
                ops.push(Mutation::RestoreFromDone { uid: uid.clone() });
                ops.push(Mutation::SetStatus {
                    uid: uid.clone(),
                    checked: false,
                    completed_on: None,
                });
            }
        }
        let link = source_link(source);
        if let (Some(text_now), Some(text_was)) =
            (strip_link(&now.text, &link), strip_link(&was.text, &link))
        {
            if text_now != text_was && source.text == text_was {
                ops.push(Mutation::EditText {
                    uid: uid.clone(),
                    text: text_now.to_string(),
                });
            }
        }
        if now.priority != was.priority && source.priority == was.priority {
            ops.push(Mutation::SetPriority {
                uid: uid.clone(),
                priority: now.priority,
            });
        }
        if now.recurrence != was.recurrence && source.recurrence == was.recurrence {
            ops.push(Mutation::SetRecurrence {
                uid: uid.clone(),
                recurrence: now.recurrence.clone(),
            });
        }
        for (field, now, was, held) in [
            (WhenField::Due, now.due, was.due, source.due),
            (WhenField::Start, now.start, was.start, source.start),
            (
                WhenField::Scheduled,
                now.scheduled,
                was.scheduled,
                source.scheduled,
            ),
        ] {
            if now != was && held == was {
                ops.push(Mutation::SetWhen {
                    uid: uid.clone(),
                    field,
                    value: now,
                });
            }
        }
        ops.extend(tail);
        if !ops.is_empty() {
            edits
                .entry(source.source.path.clone())
                .or_default()
                .extend(ops);
        }
    }
    if edited_from(current, rendered) {
        for (uid, was) in &shown {
            let Some(source) = local.get(uid) else {
                continue;
            };
            if source.source.path == own_path
                || current.body.contains(uid.as_str())
                || mirror_line(source) != was.raw
            {
                continue;
            }
            edits
                .entry(source.source.path.clone())
                .or_default()
                .push(Mutation::Delete { uid: uid.clone() });
        }
    }
    edits
}

/// The task text of a parsed mirror line: its text minus the trailing source link.
/// `None` when the link is not where the render put it (the user edited the link itself).
fn strip_link<'a>(text: &'a str, link: &str) -> Option<&'a str> {
    text.strip_suffix(link).map(str::trim_end)
}

/// `true` when `raw` has the shape of a rendered mirror line: a wikilink directly before
/// the `🆔` token. Used to recognise leftovers of the view when no other evidence exists.
pub fn looks_like_mirror(raw: &str) -> bool {
    raw.rfind("🆔")
        .map(|at| raw[..at].trim_end())
        .is_some_and(|before| before.ends_with("]]") && before.contains("[["))
}
