//! TODO.md view (§7): deterministic full-file render of the engine-owned inbox view.

use std::collections::BTreeMap;

use crate::config::VaultConfig;
use crate::domain::{LocalDate, Priority, Status, Task, TaskUid};
use crate::markdown::mutator::fmt_when;

/// First content line of every generated TODO.md (§7: right after the frontmatter block).
pub const MARKER: &str = "<!-- AUTOGENERATED BY Restask -->";

/// `- [x]` or `- [ ]` checkbox per lifecycle state.
fn checkbox(task: &Task) -> &'static str {
    match task.status {
        Status::Active => "[ ]",
        Status::Completed { .. } => "[x]",
    }
}

/// Filename without its `.md` suffix (§7 source stem).
fn stem_of(path: &str) -> &str {
    let file = path.rsplit('/').next().unwrap_or(path);
    file.strip_suffix(".md").unwrap_or(file)
}

/// The wikilink for the task's source note, or plain text when the stem is hostile (§7):
/// stems containing `[`, `]`, `|` or `#` cannot appear inside a `[[...|...]]` link, so the
/// link is replaced by plain text and a validation anomaly is logged.
fn source_link(task: &Task) -> String {
    let stem = stem_of(&task.source.path);
    let suffix = match &task.source_heading {
        Some(heading) => format!("#{heading}"),
        None => String::new(),
    };
    if stem.contains(['[', ']', '|', '#']) {
        tracing::warn!(
            uid = %task.uid,
            stem = %stem,
            "validation anomaly: hostile source stem; wikilink replaced by plain text"
        );
        format!("{stem}{suffix}")
    } else {
        format!("[[{stem}{suffix}|{stem}]]")
    }
}

/// Renders a task sourced from a vault note as a mirror line (§7):
/// `- [<check>] <text> <priority?> <🛫?><⏳?><📅?> [[<stem>#<heading>|<stem>]] 🆔 <uid>`;
/// `#<heading>` is omitted when the task has no preceding heading.
pub fn mirror_line(task: &Task) -> String {
    let mut line = format!("- {} {}", checkbox(task), task.text);
    if let Some(priority) = task.priority {
        line.push(' ');
        line.push_str(priority.emoji());
    }
    if let Some(when) = task.start {
        line.push_str(&format!(" 🛫 {}", fmt_when(when)));
    }
    if let Some(when) = task.scheduled {
        line.push_str(&format!(" ⏳ {}", fmt_when(when)));
    }
    if let Some(when) = task.due {
        line.push_str(&format!(" 📅 {}", fmt_when(when)));
    }
    line.push(' ');
    line.push_str(&source_link(task));
    line.push_str(&format!(" 🆔 {}", task.uid));
    line
}

/// Renders a TODO.md-sourced task as a full canonical line without wikilink (§7):
/// `- [<check>] <text> <priority?> <🛫?><⏳?><📅?><✅?><➕?> 🆔 <uid>`.
pub fn inbox_line(task: &Task) -> String {
    let mut line = format!("- {} {}", checkbox(task), task.text);
    if let Some(priority) = task.priority {
        line.push(' ');
        line.push_str(priority.emoji());
    }
    if let Some(when) = task.start {
        line.push_str(&format!(" 🛫 {}", fmt_when(when)));
    }
    if let Some(when) = task.scheduled {
        line.push_str(&format!(" ⏳ {}", fmt_when(when)));
    }
    if let Some(when) = task.due {
        line.push_str(&format!(" 📅 {}", fmt_when(when)));
    }
    if let Status::Completed { on } = task.status {
        line.push_str(&format!(" ✅ {}", on.format()));
    }
    if let Some(created) = task.created {
        line.push_str(&format!(" ➕ {}", created.format()));
    }
    line.push_str(&format!(" 🆔 {}", task.uid));
    line
}

/// The completion date of a task, if completed.
fn completed_on(task: &Task) -> Option<LocalDate> {
    match task.status {
        Status::Completed { on } => Some(on),
        Status::Active => None,
    }
}

/// The rendered line for a task: full canonical line for TODO.md-sourced tasks, mirror
/// line (with wikilink) for vault-note tasks.
fn line_for(task: &Task, cfg: &VaultConfig) -> String {
    if task.source.path == cfg.inbox_file {
        inbox_line(task)
    } else {
        mirror_line(task)
    }
}

/// Idempotent full render (§7). `vault_tasks` holds every routed, registered task (all
/// lists); the same task set produces byte-identical output. The file opens with the
/// `restask-list: <inbox_list>` frontmatter block (§5.2), then the marker, then the
/// `# <inbox-file-stem>` title. Sections — `## Inbox`, the five priority sections — are
/// emitted only when non-empty, in that fixed order; `## Done` is always present. `## Inbox`
/// holds active tasks without priority (ULID asc); each priority section holds active tasks
/// with that priority ((source path asc, line) asc); `## Done` holds only TODO.md-sourced
/// completed tasks newest-on-top (completed date desc, then ULID desc). Completed vault-note
/// tasks never appear (they live under their source file's Done heading), with or without a
/// priority.
pub fn render(vault_tasks: &BTreeMap<TaskUid, Task>, cfg: &VaultConfig) -> String {
    let mut inbox: Vec<&Task> = Vec::new();
    let mut prioritized: [Vec<&Task>; 5] =
        [Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new()];
    let mut done: Vec<&Task> = Vec::new();

    for task in vault_tasks.values() {
        match task.status {
            Status::Active => match task.priority {
                Some(priority) => {
                    let slot = Priority::ALL
                        .iter()
                        .position(|candidate| *candidate == priority)
                        .unwrap_or_default();
                    prioritized[slot].push(task);
                }
                None => inbox.push(task),
            },
            Status::Completed { .. } => {
                if task.source.path == cfg.inbox_file {
                    done.push(task);
                }
            }
        }
    }
    for section in &mut prioritized {
        section
            .sort_by(|a, b| (&a.source.path, a.source.line).cmp(&(&b.source.path, b.source.line)));
    }
    done.sort_by(|a, b| {
        completed_on(b)
            .cmp(&completed_on(a))
            .then_with(|| b.uid.as_str().cmp(a.uid.as_str()))
    });

    let mut out = String::new();
    out.push_str("---\nrestask-list: ");
    out.push_str(&cfg.inbox_list);
    out.push_str("\n---\n\n");
    out.push_str(MARKER);
    out.push_str("\n\n");
    out.push_str(&format!("# {}\n\n", stem_of(&cfg.inbox_file)));

    let mut sections: Vec<String> = Vec::new();
    if !inbox.is_empty() {
        let mut section = String::from("## Inbox\n");
        for task in &inbox {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    for (slot, priority) in Priority::ALL.iter().enumerate() {
        if prioritized[slot].is_empty() {
            continue;
        }
        let mut section = format!("## {} {} Priority\n", priority.emoji(), priority.heading());
        for task in &prioritized[slot] {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    {
        let mut section = String::from("## Done\n");
        for task in &done {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    out.push_str(&sections.join("\n"));
    out
}
