//! TODO.md view (§7): deterministic full-file render of the engine-owned inbox view, and
//! the reverse direction — recognising what the user edited inside it. Pure — no I/O.

use std::collections::BTreeMap;

use crate::config::VaultConfig;
use crate::domain::{LocalDate, Priority, Status, Task, TaskUid};
use crate::markdown::mutator::{canonical_line, fmt_when, Mutation, WhenField};
use crate::markdown::parser::{parse, TaskDraft};

/// First content line of every generated TODO.md (§7: right after the frontmatter block).
pub const MARKER: &str = "<!-- AUTOGENERATED BY Restask -->";

/// `[x]` or `[ ]` checkbox per lifecycle state.
fn checkbox(task: &Task) -> &'static str {
    match task.status {
        Status::Active => "[ ]",
        Status::Completed { .. } => "[x]",
    }
}

/// Filename without its `.md` suffix (§7 source stem).
fn stem_of(path: &str) -> &str {
    let file = path.rsplit('/').next().unwrap_or(path);
    file.strip_suffix(".md").unwrap_or(file)
}

/// The wikilink for the task's source note, or plain text when the stem is hostile (§7):
/// stems containing `[`, `]`, `|` or `#` cannot appear inside a `[[...|...]]` link, so the
/// link is replaced by plain text.
fn source_link(task: &Task) -> String {
    let stem = stem_of(&task.source.path);
    let suffix = match &task.source_heading {
        Some(heading) => format!("#{heading}"),
        None => String::new(),
    };
    if stem.contains(['[', ']', '|', '#']) {
        format!("{stem}{suffix}")
    } else {
        format!("[[{stem}{suffix}|{stem}]]")
    }
}

/// Renders a task sourced from a vault note as a mirror line (§7):
/// `- [<check>] <text> <priority?> <🔁?><🛫?><⏳?><📅?> [[<stem>#<heading>|<stem>]] 🆔 <uid>`;
/// `#<heading>` is omitted when the task has no preceding heading.
pub fn mirror_line(task: &Task) -> String {
    let mut parts: Vec<String> = vec![format!("- {}", checkbox(task))];
    if !task.text.is_empty() {
        parts.push(task.text.clone());
    }
    if let Some(priority) = task.priority {
        parts.push(priority.emoji().to_string());
    }
    if let Some(rule) = &task.recurrence {
        parts.push(format!("🔁 {}", rule.to_text()));
    }
    if let Some(when) = task.start {
        parts.push(format!("🛫 {}", fmt_when(when)));
    }
    if let Some(when) = task.scheduled {
        parts.push(format!("⏳ {}", fmt_when(when)));
    }
    if let Some(when) = task.due {
        parts.push(format!("📅 {}", fmt_when(when)));
    }
    parts.push(source_link(task));
    parts.push(format!("🆔 {}", task.uid));
    parts.join(" ")
}

/// Renders a TODO.md-sourced task as a full canonical line without wikilink (§7):
/// `- [<check>] <text> <priority?> <🛫?><⏳?><📅?><✅?><➕?> 🆔 <uid>`.
pub fn inbox_line(task: &Task) -> String {
    canonical_line("", '-', &TaskDraft::from(task))
}

/// The completion date of a task, if completed.
fn completed_on(task: &Task) -> Option<LocalDate> {
    match task.status {
        Status::Completed { on } => Some(on),
        Status::Active => None,
    }
}

/// The rendered line for a task: full canonical line for TODO.md-sourced tasks, mirror
/// line (with wikilink) for vault-note tasks.
fn line_for(task: &Task, cfg: &VaultConfig) -> String {
    if task.source.path == cfg.inbox_file {
        inbox_line(task)
    } else {
        mirror_line(task)
    }
}

/// Idempotent full render (§7). `vault_tasks` holds every routed, registered task (all
/// lists); the same task set produces byte-identical output. The file opens with the
/// `restask-list: <inbox_list>` frontmatter block (§5.2), then the marker, then the
/// `# <inbox-file-stem>` title. Sections — `## Inbox`, the five priority sections — are
/// emitted only when non-empty, in that fixed order; `## Done` is always present. `## Inbox`
/// holds active tasks without priority (ULID asc); each priority section holds active tasks
/// with that priority ((source path asc, line) asc); `## Done` holds only TODO.md-sourced
/// completed tasks newest-on-top (completed date desc, then ULID desc). Completed vault-note
/// tasks never appear (they live under their source file's Done heading), with or without a
/// priority.
pub fn render(vault_tasks: &BTreeMap<TaskUid, Task>, cfg: &VaultConfig) -> String {
    let mut inbox: Vec<&Task> = Vec::new();
    let mut prioritized: [Vec<&Task>; 5] =
        [Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new()];
    let mut done: Vec<&Task> = Vec::new();

    for task in vault_tasks.values() {
        match task.status {
            Status::Active => match task.priority {
                Some(priority) => {
                    let slot = Priority::ALL
                        .iter()
                        .position(|candidate| *candidate == priority)
                        .unwrap_or_default();
                    prioritized[slot].push(task);
                }
                // The inbox section is the inbox file's own unprioritized tasks; an
                // unprioritized note task stays in its note only (README).
                None if task.source.path == cfg.inbox_file => inbox.push(task),
                None => {}
            },
            Status::Completed { .. } => {
                if task.source.path == cfg.inbox_file {
                    done.push(task);
                }
            }
        }
    }
    for section in &mut prioritized {
        section
            .sort_by(|a, b| (&a.source.path, a.source.line).cmp(&(&b.source.path, b.source.line)));
    }
    done.sort_by(|a, b| {
        completed_on(b)
            .cmp(&completed_on(a))
            .then_with(|| b.uid.as_str().cmp(a.uid.as_str()))
    });

    let mut out = String::new();
    out.push_str("---\nrestask-list: ");
    out.push_str(&cfg.inbox_list);
    out.push_str("\n---\n\n");
    out.push_str(MARKER);
    out.push_str("\n\n");
    out.push_str(&format!("# {}\n\n", stem_of(&cfg.inbox_file)));

    let mut sections: Vec<String> = Vec::new();
    if !inbox.is_empty() {
        let mut section = String::from("## Inbox\n");
        for task in &inbox {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    for (slot, priority) in Priority::ALL.iter().enumerate() {
        if prioritized[slot].is_empty() {
            continue;
        }
        let mut section = format!("## {} {} Priority\n", priority.emoji(), priority.heading());
        for task in &prioritized[slot] {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    {
        let mut section = String::from("## Done\n");
        for task in &done {
            section.push_str(&line_for(task, cfg));
            section.push('\n');
        }
        sections.push(section);
    }
    out.push_str(&sections.join("\n"));
    out
}

/// What the user changed on **mirror lines** inside TODO.md since the engine last rendered
/// it, expressed as mutations on the source notes (keyed by vault-relative path).
///
/// A mirror line is "the exact same task" as its source line (README), so checking it
/// off, re-prioritizing it, re-dating it or rewording it in TODO.md must reach the note.
/// `rendered` is the engine's own last render; a mirror line that still equals it was not
/// touched (it may merely be stale, which the next render fixes). A field the user changed
/// is applied only when the source still shows the rendered value — if the note changed
/// that field too, the note wins.
pub fn mirror_edits(
    current: &str,
    rendered: &str,
    local: &BTreeMap<TaskUid, Task>,
    cfg: &VaultConfig,
    today: LocalDate,
) -> BTreeMap<String, Vec<Mutation>> {
    let mut edits: BTreeMap<String, Vec<Mutation>> = BTreeMap::new();
    if current == rendered {
        return edits;
    }
    let mut shown: BTreeMap<TaskUid, TaskDraft> = BTreeMap::new();
    for task in parse(rendered, cfg).tasks {
        if let Some(uid) = task.draft.uid.clone() {
            shown.entry(uid).or_insert(task.draft);
        }
    }
    let mut seen: Vec<TaskUid> = Vec::new();
    for line in parse(current, cfg).tasks {
        let now = line.draft;
        let Some(uid) = now.uid.clone() else {
            continue;
        };
        let (Some(source), Some(was)) = (local.get(&uid), shown.get(&uid)) else {
            continue;
        };
        if source.source.path == cfg.inbox_file || seen.contains(&uid) {
            continue;
        }
        seen.push(uid.clone());
        let mut ops: Vec<Mutation> = Vec::new();
        let mut tail: Vec<Mutation> = Vec::new();

        let source_checked = matches!(source.status, Status::Completed { .. });
        if now.checked != was.checked && source_checked == was.checked {
            if now.checked {
                ops.push(Mutation::SetStatus {
                    uid: uid.clone(),
                    checked: true,
                    completed_on: Some(now.completed_on.unwrap_or(today)),
                });
                tail.push(Mutation::MoveToDone { uid: uid.clone() });
            } else {
                ops.push(Mutation::RestoreFromDone { uid: uid.clone() });
                ops.push(Mutation::SetStatus {
                    uid: uid.clone(),
                    checked: false,
                    completed_on: None,
                });
            }
        }
        let link = source_link(source);
        if let (Some(text_now), Some(text_was)) =
            (strip_link(&now.text, &link), strip_link(&was.text, &link))
        {
            if text_now != text_was && source.text == text_was {
                ops.push(Mutation::EditText {
                    uid: uid.clone(),
                    text: text_now.to_string(),
                });
            }
        }
        if now.priority != was.priority && source.priority == was.priority {
            ops.push(Mutation::SetPriority {
                uid: uid.clone(),
                priority: now.priority,
            });
        }
        if now.recurrence != was.recurrence && source.recurrence == was.recurrence {
            ops.push(Mutation::SetRecurrence {
                uid: uid.clone(),
                recurrence: now.recurrence.clone(),
            });
        }
        for (field, now, was, held) in [
            (WhenField::Due, now.due, was.due, source.due),
            (WhenField::Start, now.start, was.start, source.start),
            (
                WhenField::Scheduled,
                now.scheduled,
                was.scheduled,
                source.scheduled,
            ),
        ] {
            if now != was && held == was {
                ops.push(Mutation::SetWhen {
                    uid: uid.clone(),
                    field,
                    value: now,
                });
            }
        }
        ops.extend(tail);
        if !ops.is_empty() {
            edits
                .entry(source.source.path.clone())
                .or_default()
                .extend(ops);
        }
    }
    edits
}

/// The task text of a parsed mirror line: its text minus the trailing source link.
/// `None` when the link is not where the render put it (the user edited the link itself).
fn strip_link<'a>(text: &'a str, link: &str) -> Option<&'a str> {
    text.strip_suffix(link).map(str::trim_end)
}

/// `true` when `raw` has the shape of a rendered mirror line: a wikilink directly before
/// the `🆔` token. Used to recognise leftovers of the view when no other evidence exists.
pub fn looks_like_mirror(raw: &str) -> bool {
    raw.rfind("🆔")
        .map(|at| raw[..at].trim_end())
        .is_some_and(|before| before.ends_with("]]") && before.contains("[["))
}
